spring:
  datasource:
    # Use quotes because of : and ? in the URL
    url: "jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: Root123
  jpa:
    hibernate:
      ddl-auto: update    # Automatically creates/updates tables based on entities
    show-sql: true        # Shows SQL statements in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.example.user_service: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.lang.RuntimeException    # Retry only on these exceptions
        ignoreExceptions:
            - com.example.user_service.exception.ResourceNotFoundException
  ratelimiter:
    instances:
      userService:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    enable:
      all: true

#redis:
#  host: localhost
#  port: 6379
#  password: # optional
#  cache:
#    type: redis